// Generated by build_art_data.py — do not edit by hand.
// Re-run "python3 build_art_data.py" after adding/removing files in
// ascii_art/ or image_art/, so momentum.html also works offline
// (opened directly as a file://, with no server running).
window.ART_DATA = {
  "generatedAt": "2026-08-11T16:15:55.024352+00:00",
  "ascii": {
    "artworks": [
      {
        "id": "flower",
        "name": "Wildflower",
        "category": "nature",
        "file": "nature/flower.txt",
        "revealTasks": 5,
        "content": "              \\\\   |   //\n               \\\\  |  //\n            --   \\\\|//   --\n               (   ***   )\n            --   //|\\\\   --\n               //  |  \\\\\n              //   |   \\\\\n                   |\n                  /|\\\n                 / | \\\n                /  |  \\\n                   |\n                  (=)\n                 (===)\n"
      },
      {
        "id": "mountain",
        "name": "Mountain Peak",
        "category": "nature",
        "file": "nature/mountain.txt",
        "revealTasks": 6,
        "content": "                        _\n                      _/ \\_\n                     (  o  )\n                      \\_ _/\n        /\\            /\\\n       /  \\          /  \\        /\\\n      /    \\        /    \\      /  \\\n     /      \\      /      \\    /    \\\n    /        \\    /        \\  /      \\\n   /__________\\  /__________\\/________\\\n  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
      },
      {
        "id": "tree",
        "name": "Old Oak",
        "category": "nature",
        "file": "nature/tree.txt",
        "revealTasks": 8,
        "content": "                 &&&&&&&\n             &&&&&&&&&&&&&&&\n          &&&&&&&&&&&&&&&&&&&&&\n        &&&&&&&&&&&&&&&&&&&&&&&&&\n       &&&&&&&&&&&&&&&&&&&&&&&&&&&\n        &&&&&&&&&&&&&&&&&&&&&&&&&\n          &&&&&&&&&&&&&&&&&&&&&\n             &&&&&&&&&&&&&&&\n                 &&&&&&&\n                   ||||\n                   ||||\n                  //||\\\\\n                 // || \\\\\n                //  ||  \\\\\n"
      }
    ]
  },
  "image": {
    "images": [
      {
        "id": "desert-dunes",
        "name": "Desert Dunes",
        "category": "nature",
        "file": "examples/desert-dunes.jpg",
        "revealTasks": 8,
        "grid": {
          "cols": 8,
          "rows": 5
        },
        "source": null,
        "license": "own work",
        "credit": "Made for this project",
        "note": null
      },
      {
        "id": "forest",
        "name": "Forest Path",
        "category": "nature",
        "file": "examples/forest.svg",
        "revealTasks": 6,
        "grid": {
          "cols": 5,
          "rows": 4
        },
        "source": null,
        "license": "own work",
        "credit": "Made for this project",
        "note": null
      },
      {
        "id": "li-moly-2091",
        "name": "Li Moly 2091",
        "category": "examples",
        "file": "examples/li-moly-2091.jpg",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "unknown",
        "credit": null,
        "note": "unresolved — identify the source, or remove before publishing"
      },
      {
        "id": "meadow",
        "name": "Rolling Meadow",
        "category": "nature",
        "file": "examples/meadow.png",
        "revealTasks": 7,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "own work",
        "credit": "Made for this project",
        "note": null
      },
      {
        "id": "nadi-wind-18-1",
        "name": "Nadi Wind 18 1",
        "category": "examples",
        "file": "examples/nadi_wind-18-1.jpg",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "unknown",
        "credit": null,
        "note": "unresolved — identify the source, or remove before publishing"
      },
      {
        "id": "ocean-night",
        "name": "Starry Ocean Night",
        "category": "nature",
        "file": "examples/ocean-night.svg",
        "revealTasks": 9,
        "grid": {
          "cols": 6,
          "rows": 5
        },
        "source": null,
        "license": "own work",
        "credit": "Made for this project",
        "note": null
      },
      {
        "id": "sunset",
        "name": "Desert Sunset",
        "category": "nature",
        "file": "examples/sunset.svg",
        "revealTasks": 8,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "own work",
        "credit": "Made for this project",
        "note": null
      },
      {
        "id": "00027-143724114",
        "name": "00027 143724114",
        "category": "stable_diffusion",
        "file": "stable_diffusion/00027-143724114.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "00044-3453245357",
        "name": "00044 3453245357",
        "category": "stable_diffusion",
        "file": "stable_diffusion/00044-3453245357.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "00056-2661726201",
        "name": "00056 2661726201",
        "category": "stable_diffusion",
        "file": "stable_diffusion/00056-2661726201.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "00148-1774344079",
        "name": "00148 1774344079",
        "category": "stable_diffusion",
        "file": "stable_diffusion/00148-1774344079.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "2024-08-15-17-37-img-0331",
        "name": "2024 08 15 17 37 IMG 0331",
        "category": "stable_diffusion",
        "file": "stable_diffusion/2024_08_15_17_37_IMG_0331.JPG",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "unknown",
        "credit": null,
        "note": "camera-style IMG_ filename in the stable_diffusion folder — likely misfiled"
      },
      {
        "id": "010-i-don-t-give-a-shit-warm",
        "name": "010 I Don't Give A Shit Warm",
        "category": "stable_diffusion",
        "file": "stable_diffusion/_010_I don't give a shit_warm.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "011-auntitled-2-warm",
        "name": "011 Auntitled 2 Warm",
        "category": "stable_diffusion",
        "file": "stable_diffusion/_011_aUntitled_2_warm.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "022-00028-4013610666",
        "name": "022 00028 4013610666",
        "category": "stable_diffusion",
        "file": "stable_diffusion/_022_00028-4013610666.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      },
      {
        "id": "025-00036-2941276205e-warm",
        "name": "025 00036 2941276205e Warm",
        "category": "stable_diffusion",
        "file": "stable_diffusion/_025_00036-2941276205e_warm.png",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        },
        "source": null,
        "license": "AI-generated",
        "credit": "Generated by the project author with Stable Diffusion",
        "note": "no human authorship — not copyrightable in the US; no rights asserted"
      }
    ]
  }
};
