// Generated by build_art_data.py — do not edit by hand.
// Re-run "python3 build_art_data.py" after adding/removing files in
// ascii_art/ or image_art/, so momentum.html also works offline
// (opened directly as a file://, with no server running).
window.ART_DATA = {
  "generatedAt": "2026-08-05T14:21:57.465588+00:00",
  "ascii": {
    "artworks": [
      {
        "id": "flower",
        "name": "Wildflower",
        "category": "nature",
        "file": "nature/flower.txt",
        "revealTasks": 5,
        "content": "              \\\\   |   //\n               \\\\  |  //\n            --   \\\\|//   --\n               (   ***   )\n            --   //|\\\\   --\n               //  |  \\\\\n              //   |   \\\\\n                   |\n                  /|\\\n                 / | \\\n                /  |  \\\n                   |\n                  (=)\n                 (===)\n"
      },
      {
        "id": "mountain",
        "name": "Mountain Peak",
        "category": "nature",
        "file": "nature/mountain.txt",
        "revealTasks": 6,
        "content": "                        _\n                      _/ \\_\n                     (  o  )\n                      \\_ _/\n        /\\            /\\\n       /  \\          /  \\        /\\\n      /    \\        /    \\      /  \\\n     /      \\      /      \\    /    \\\n    /        \\    /        \\  /      \\\n   /__________\\  /__________\\/________\\\n  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
      },
      {
        "id": "tree",
        "name": "Old Oak",
        "category": "nature",
        "file": "nature/tree.txt",
        "revealTasks": 8,
        "content": "                 &&&&&&&\n             &&&&&&&&&&&&&&&\n          &&&&&&&&&&&&&&&&&&&&&\n        &&&&&&&&&&&&&&&&&&&&&&&&&\n       &&&&&&&&&&&&&&&&&&&&&&&&&&&\n        &&&&&&&&&&&&&&&&&&&&&&&&&\n          &&&&&&&&&&&&&&&&&&&&&\n             &&&&&&&&&&&&&&&\n                 &&&&&&&\n                   ||||\n                   ||||\n                  //||\\\\\n                 // || \\\\\n                //  ||  \\\\\n"
      }
    ]
  },
  "image": {
    "images": [
      {
        "id": "desert-dunes",
        "name": "Desert Dunes",
        "category": "nature",
        "file": "examples/desert-dunes.jpg",
        "revealTasks": 8,
        "grid": {
          "cols": 8,
          "rows": 5
        }
      },
      {
        "id": "forest",
        "name": "Forest Path",
        "category": "nature",
        "file": "examples/forest.svg",
        "revealTasks": 6,
        "grid": {
          "cols": 5,
          "rows": 4
        }
      },
      {
        "id": "li-moly-2091",
        "name": "Li Moly 2091",
        "category": "examples",
        "file": "examples/li-moly-2091.jpg",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        }
      },
      {
        "id": "meadow",
        "name": "Rolling Meadow",
        "category": "nature",
        "file": "examples/meadow.png",
        "revealTasks": 7,
        "grid": {
          "cols": 6,
          "rows": 4
        }
      },
      {
        "id": "nadi-wind-18-1",
        "name": "Nadi Wind 18 1",
        "category": "examples",
        "file": "examples/nadi_wind-18-1.jpg",
        "revealTasks": 6,
        "grid": {
          "cols": 6,
          "rows": 4
        }
      },
      {
        "id": "ocean-night",
        "name": "Starry Ocean Night",
        "category": "nature",
        "file": "examples/ocean-night.svg",
        "revealTasks": 9,
        "grid": {
          "cols": 6,
          "rows": 5
        }
      },
      {
        "id": "sunset",
        "name": "Desert Sunset",
        "category": "nature",
        "file": "examples/sunset.svg",
        "revealTasks": 8,
        "grid": {
          "cols": 6,
          "rows": 4
        }
      },
      {
        "id": "ember-canyon",
        "name": "Ember Canyon",
        "category": "landscape",
        "file": "nature/-6947ee62e6456d553347d5.jpg",
        "revealTasks": 9,
        "grid": {
          "cols": 8,
          "rows": 4
        }
      }
    ]
  }
};
