#!/usr/bin/env python3
"""
Regenerates IMAGE_CREDITS.md from image_art/manifest.json.

Every image shipped in this repo needs a recorded source and licence — partly so
the ones that require attribution actually get it (CC BY, for instance, is free to
use but *only* with credit), and partly so "where did this come from?" never has to
be answered from memory again.

The manifest carries three provenance fields per image, alongside the display ones:

    "source":  where it came from (URL), or null
    "license": short token — "CC-BY-4.0", "Unsplash License", "own work",
               "AI-generated", or "unknown"
    "credit":  the attribution line to reproduce, or null
    "note":    anything a reader needs to know; on an "unknown" entry, what to do

This walks image_art/ rather than the manifest, so a file dropped in without a
manifest entry shows up as unrecorded instead of silently shipping uncredited.

Usage: python3 build_credits.py           # write IMAGE_CREDITS.md
       python3 build_credits.py --check   # exit 1 if anything is unresolved
"""
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent
IMAGE_DIR = ROOT / 'image_art'
OUT_PATH = ROOT / 'IMAGE_CREDITS.md'
# deliberately wider than the app's own extension list: a file can sit in the repo,
# and therefore need crediting, without the app being able to display it.
IMAGE_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.svg', '.webp', '.gif', '.avif')
# licences that carry an attribution condition — these get their credit line printed
# in full, since reproducing it is the actual term of use.
ATTRIBUTION_REQUIRED = {'CC-BY-4.0', 'CC-BY-SA-4.0', 'CC-BY-3.0'}
UNRESOLVED = 'unknown'


def load_manifest():
    path = IMAGE_DIR / 'manifest.json'
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding='utf-8'))
    return {e['file']: e for e in data.get('images', []) if 'file' in e}


def discover():
    return sorted(
        p.relative_to(IMAGE_DIR).as_posix()
        for p in IMAGE_DIR.rglob('*')
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    )


def describe(file, entry):
    """(licence, credit, source, note) with the unrecorded case folded in."""
    if entry is None:
        return (UNRESOLVED, None, None,
                'no manifest entry — add one recording where this came from')
    return (entry.get('license') or UNRESOLVED, entry.get('credit'),
            entry.get('source'), entry.get('note'))


def main():
    manifest = load_manifest()
    files = discover()

    groups = {}
    unresolved = []
    for file in files:
        licence, credit, source, note = describe(file, manifest.get(file))
        row = {'file': file, 'credit': credit, 'source': source, 'note': note}
        if licence == UNRESOLVED:
            unresolved.append(row)
        else:
            groups.setdefault(licence, []).append(row)

    md = []
    md.append('# Image credits')
    md.append('')
    md.append('Generated by `python3 build_credits.py` — do not edit by hand; record the')
    md.append('facts in `image_art/manifest.json` and re-run. Covers every image file in')
    md.append(f'`image_art/`, whether or not the app currently displays it. Last run: {date.today().isoformat()}.')
    md.append('')
    md.append(f'{len(files)} image{"" if len(files) == 1 else "s"}, '
              f'{len(files) - len(unresolved)} with a recorded licence, '
              f'{len(unresolved)} unresolved.')
    md.append('')

    if unresolved:
        md.append('## Unresolved — resolve or remove before publishing')
        md.append('')
        md.append('Provenance for these is not established. Anything created by a person is')
        md.append('copyrighted automatically, so "no licence recorded" means "no permission')
        md.append('established", not "free to use".')
        md.append('')
        md.append('| file | what to do |')
        md.append('| --- | --- |')
        for r in unresolved:
            md.append(f'| `{r["file"]}` | {r["note"] or "identify the source, or remove it"} |')
        md.append('')

    for licence in sorted(groups):
        rows = groups[licence]
        heading = f'## {licence} ({len(rows)})'
        if licence in ATTRIBUTION_REQUIRED:
            heading += ' — attribution required'
        md.append(heading)
        md.append('')
        if licence in ATTRIBUTION_REQUIRED:
            md.append('Free to use **provided the credit below is reproduced**. Keep these lines')
            md.append('with the images if you redistribute them.')
            md.append('')
        md.append('| file | credit | source |')
        md.append('| --- | --- | --- |')
        for r in rows:
            credit = r['credit'] or '—'
            source = f'[link]({r["source"]})' if r['source'] else '—'
            md.append(f'| `{r["file"]}` | {credit} | {source} |')
        md.append('')
        notes = {r['note'] for r in rows if r['note']}
        for note in sorted(notes):
            md.append(f'- {note}')
        if notes:
            md.append('')

    OUT_PATH.write_text('\n'.join(md), encoding='utf-8')
    print(f'wrote {OUT_PATH} ({len(files)} images, {len(unresolved)} unresolved)')
    for r in unresolved:
        print(f'  unresolved: {r["file"]}')

    if '--check' in sys.argv and unresolved:
        print(f'\n--check: {len(unresolved)} image(s) without an established licence')
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
