#!/usr/bin/env python3
"""
Regenerates art-data.js by scanning ascii_art/ and image_art/ for files,
the same way momentum.html's live directory-discovery does when served over
http. Run this after adding/removing/renaming files in either folder so the
app also works when momentum.html is opened directly (file://), where the
browser can't fetch() a directory listing or read local .txt files at all.

Usage: python3 build_art_data.py
"""
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
ASCII_DIR = ROOT / 'ascii_art'
IMAGE_DIR = ROOT / 'image_art'
ASCII_EXTENSIONS = ('.txt',)
IMAGE_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.svg', '.webp', '.gif')


def slugify(name):
    s = re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')
    return s or 'artwork'


def humanize_name(stem):
    words = [w for w in re.split(r'[-_\s]+', stem) if w]
    if not words:
        return stem
    # drop purely-numeric tokens (track/page numbering like "062" in "062 Cottage
    # And Christmas Tree Night") — but only when doing so leaves something behind;
    # an all-numeric stem (e.g. "00027-143724114") has no title to fall back to.
    worded = [w for w in words if not re.fullmatch(r'\d+', w)]
    words = worded or words
    out = []
    for w in words:
        if w == w.upper() and re.search(r'[A-Z]', w):
            out.append(w)
        else:
            out.append(w[0].upper() + w[1:].lower())
    return ' '.join(out)


def discover_files(base_dir, extensions):
    files = []
    for path in base_dir.rglob('*'):
        if path.is_file() and path.suffix.lower() in extensions:
            files.append(path.relative_to(base_dir).as_posix())
    return sorted(files)


def load_overrides(manifest_path, items_field):
    if not manifest_path.exists():
        return {}
    data = json.loads(manifest_path.read_text(encoding='utf-8'))
    return {e['file']: e for e in data.get(items_field, []) if 'file' in e}


def build_entries(base_dir, extensions, manifest_path, items_field, default_extra=None):
    default_extra = default_extra or {}
    files = discover_files(base_dir, extensions)
    overrides = load_overrides(manifest_path, items_field)
    used_ids = set()
    entries = []
    for file in files:
        override = overrides.get(file, {})
        stem = Path(file).stem
        folder = str(Path(file).parent) if Path(file).parent != Path('.') else None
        base_id = override.get('id') or slugify(stem)
        entry_id, n = base_id, 2
        while entry_id in used_ids:
            entry_id = f'{base_id}-{n}'
            n += 1
        used_ids.add(entry_id)
        entry = {
            'id': entry_id,
            'name': humanize_name(stem),
            'category': folder,
            'file': file,
            'revealTasks': 6,
        }
        entry.update(default_extra)
        entry.update(override)
        entry['file'] = file
        entries.append(entry)
    return entries


def main():
    ascii_entries = build_entries(
        ASCII_DIR, ASCII_EXTENSIONS, ASCII_DIR / 'manifest.json', 'artworks',
    )
    for entry in ascii_entries:
        entry['content'] = (ASCII_DIR / entry['file']).read_text(encoding='utf-8')

    image_entries = build_entries(
        IMAGE_DIR, IMAGE_EXTENSIONS, IMAGE_DIR / 'manifest.json', 'images',
        default_extra={'grid': {'cols': 6, 'rows': 4}},
    )

    art_data = {
        # read by momentum.html to detect when this snapshot has drifted from what's
        # actually on disk: if you're serving the app over http (where it can list
        # the folders live) and that live listing turns up files this snapshot
        # doesn't know about, it's a sign you added art and forgot to rerun this
        # script — the offline (file://) copy would silently keep showing the old
        # set. the notice names this timestamp so you know how out of date it is.
        'generatedAt': datetime.now(timezone.utc).isoformat(),
        'ascii': {'artworks': ascii_entries},
        'image': {'images': image_entries},
    }

    out_path = ROOT / 'art-data.js'
    js = (
        '// Generated by build_art_data.py — do not edit by hand.\n'
        '// Re-run "python3 build_art_data.py" after adding/removing files in\n'
        '// ascii_art/ or image_art/, so momentum.html also works offline\n'
        '// (opened directly as a file://, with no server running).\n'
        'window.ART_DATA = ' + json.dumps(art_data, indent=2, ensure_ascii=False) + ';\n'
    )
    out_path.write_text(js, encoding='utf-8')
    print(f'wrote {out_path} ({len(ascii_entries)} ascii artworks, {len(image_entries)} images)')


if __name__ == '__main__':
    main()
