// Generated by build_font_data.py — do not edit by hand.
// Re-run "python3 build_font_data.py" after adding or removing files in
// fonts/, so the "font" command sees them (and so the app still works
// offline, opened directly as a file:// with no server running).
window.FONT_DATA = {
  "generatedAt": "2026-08-18T09:41:40.139691+00:00",
  "families": [
    {
      "id": "anonymous-pro",
      "family": "Anonymous Pro",
      "name": "Anonymous Pro",
      "category": "modern",
      "files": [
        {
          "file": "fonts/modern/anonymous-pro-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/modern/anonymous-pro-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "azeret-mono",
      "family": "Azeret Mono",
      "name": "Azeret Mono",
      "category": "character",
      "files": [
        {
          "file": "fonts/character/azeret-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/character/azeret-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "b612-mono",
      "family": "B612 Mono",
      "name": "B612 Mono",
      "category": "futuristic",
      "files": [
        {
          "file": "fonts/futuristic/b612-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/futuristic/b612-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "courier-prime",
      "family": "Courier Prime",
      "name": "Courier Prime",
      "category": "retro",
      "files": [
        {
          "file": "fonts/retro/courier-prime-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/retro/courier-prime-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "cutive-mono",
      "family": "Cutive Mono",
      "name": "Cutive Mono",
      "category": "retro",
      "files": [
        {
          "file": "fonts/retro/cutive-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        }
      ]
    },
    {
      "id": "dm-mono",
      "family": "DM Mono",
      "name": "DM Mono",
      "category": "character",
      "files": [
        {
          "file": "fonts/character/dm-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        }
      ]
    },
    {
      "id": "fira-code",
      "family": "Fira Code",
      "name": "Fira Code",
      "category": "modern",
      "files": [
        {
          "file": "fonts/modern/fira-code-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/modern/fira-code-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "ibm-plex-mono",
      "family": "IBM Plex Mono",
      "name": "IBM Plex Mono",
      "category": null,
      "files": [
        {
          "file": "fonts/ibm-plex-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/ibm-plex-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "inconsolata",
      "family": "Inconsolata",
      "name": "Inconsolata",
      "category": "modern",
      "files": [
        {
          "file": "fonts/modern/inconsolata-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/modern/inconsolata-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "jetbrains-mono",
      "family": "JetBrains Mono",
      "name": "JetBrains Mono",
      "category": "modern",
      "files": [
        {
          "file": "fonts/modern/jetbrains-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/modern/jetbrains-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "kode-mono",
      "family": "Kode Mono",
      "name": "Kode Mono",
      "category": "futuristic",
      "files": [
        {
          "file": "fonts/futuristic/kode-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/futuristic/kode-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "martian-mono",
      "family": "Martian Mono",
      "name": "Martian Mono",
      "category": "futuristic",
      "files": [
        {
          "file": "fonts/futuristic/martian-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/futuristic/martian-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "roboto-mono",
      "family": "Roboto Mono",
      "name": "Roboto Mono",
      "category": "modern",
      "files": [
        {
          "file": "fonts/modern/roboto-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/modern/roboto-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "share-tech-mono",
      "family": "Share Tech Mono",
      "name": "Share Tech Mono",
      "category": "retro",
      "files": [
        {
          "file": "fonts/retro/share-tech-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        }
      ]
    },
    {
      "id": "source-code-pro",
      "family": "Source Code Pro",
      "name": "Source Code Pro",
      "category": "modern",
      "files": [
        {
          "file": "fonts/modern/source-code-pro-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/modern/source-code-pro-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "space-mono",
      "family": "Space Mono",
      "name": "Space Mono",
      "category": "retro",
      "files": [
        {
          "file": "fonts/retro/space-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        },
        {
          "file": "fonts/retro/space-mono-700.woff2",
          "format": "woff2",
          "weight": 700,
          "style": "normal"
        }
      ]
    },
    {
      "id": "syne-mono",
      "family": "Syne Mono",
      "name": "Syne Mono",
      "category": "character",
      "files": [
        {
          "file": "fonts/character/syne-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        }
      ]
    },
    {
      "id": "vt323",
      "family": "VT323",
      "name": "VT323",
      "category": "retro",
      "files": [
        {
          "file": "fonts/retro/vt323-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        }
      ]
    },
    {
      "id": "xanh-mono",
      "family": "Xanh Mono",
      "name": "Xanh Mono",
      "category": "character",
      "files": [
        {
          "file": "fonts/character/xanh-mono-400.woff2",
          "format": "woff2",
          "weight": 400,
          "style": "normal"
        }
      ]
    }
  ]
};
